-- AlterTable
ALTER TABLE `notifications`
    MODIFY `type` ENUM('FOLLOW_UP_DUE', 'FOLLOW_UP_OVERDUE', 'VERIFICATION_REQUIRED', 'LICENSURE_RESULT_REQUIRED', 'VALIDATION_ERROR', 'IMPROVEMENT_PLAN_TASK_DUE', 'PROGRAM_BELOW_THRESHOLD', 'MISSING_OUTCOMES_DIGEST', 'SCHEDULED_REPORT_READY', 'REPORT_EXPORT_READY', 'BACKUP_STALE', 'PROGRAM_AT_RISK') NOT NULL;

-- CreateTable
CREATE TABLE `at_risk_alerts` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `reporting_period_id` INTEGER NOT NULL,
    `program_id` INTEGER NOT NULL,
    `metric` ENUM('COMPLETION', 'PLACEMENT', 'LICENSURE') NOT NULL,
    `kind` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `at_risk_alerts_key`(`reporting_period_id`, `program_id`, `metric`, `kind`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
