-- AlterTable
ALTER TABLE `communication_events` MODIFY `event_type` ENUM('FOLLOW_UP_ATTEMPT', 'GRADUATE_SURVEY_SENT', 'GRADUATE_SURVEY_RESPONSE', 'EMPLOYER_SURVEY_SENT', 'EMPLOYER_SURVEY_RESPONSE', 'VERIFICATION_CONTACT', 'NOTIFICATION') NOT NULL;
