import {
  CPL_METRICS,
  RECOMPUTE_MIN_INTERVAL_MINUTES,
  RISK_STATUS_LABELS,
} from "@outcomelink/shared";
import type { Request, Response } from "express";
import { z } from "zod";
import { getAccessibleProgramIds } from "../../lib/accessScope";
import { ApiError } from "../../lib/apiError";
import { sendData } from "../../lib/apiResponse";
import { DEFAULT_BACKOFF_MS, registerJob, runJob } from "../../lib/jobRunner";
import {
  buildProvenanceSheet,
  describeGeneratedBy,
  describePeriods,
  formatTimestamp,
} from "../../lib/provenance";
import { prisma } from "../../lib/prisma";
import { sendXlsx, type XlsxSheet } from "../../lib/xlsx";
import { computeReportingPeriod } from "../accreditation/calculators/cplCalculator";
import { assertPeriodIsEditable } from "../accreditation/reportingPeriods";
import { runValidation } from "../accreditation/validators/validationEngine";
import { buildProgramDashboard } from "./programDashboard";

export const dashboardQuerySchema = z.object({
  reportingPeriodId: z.coerce.number().int().positive().optional(),
});
type DashboardQuery = z.infer<typeof dashboardQuerySchema>;

async function loadDashboard(req: Request) {
  const { reportingPeriodId } = req.query as unknown as DashboardQuery;
  const dashboard = await buildProgramDashboard(
    req.user!.institutionId,
    await getAccessibleProgramIds(req.user!),
    reportingPeriodId,
  );
  if (reportingPeriodId && !dashboard.period) throw ApiError.notFound("Reporting period not found");
  return dashboard;
}

export async function show(req: Request, res: Response) {
  sendData(res, await loadDashboard(req));
}

const METRIC_LABELS = {
  COMPLETION: "Completion",
  PLACEMENT: "Placement",
  LICENSURE: "Licensure",
} as const;

/** The dashboard's program table as .xlsx, with the "Report Info" provenance sheet like every other export. */
export async function exportDashboard(req: Request, res: Response) {
  const dashboard = await loadDashboard(req);
  if (!dashboard.period) throw ApiError.badRequest("There is no reporting period to export yet");

  const columns = [
    { header: "Program", key: "program", width: 32 },
    { header: "Campus", key: "campus", width: 20 },
    { header: "Overall status", key: "overall", width: 18 },
    ...CPL_METRICS.flatMap((metric) => [
      { header: `${METRIC_LABELS[metric]} %`, key: `${metric}-rate`, width: 14 },
      { header: `${METRIC_LABELS[metric]} benchmark %`, key: `${metric}-benchmark`, width: 18 },
      { header: `${METRIC_LABELS[metric]} status`, key: `${metric}-status`, width: 18 },
      { header: `${METRIC_LABELS[metric]} successes needed`, key: `${metric}-needed`, width: 20 },
    ]),
    { header: "Open validation issues", key: "issues", width: 20 },
    { header: "Graduates with no outcome / seeking", key: "unresolved", width: 28 },
  ];
  const rows = dashboard.programs.map((program) => {
    const row: Record<string, unknown> = {
      program: program.name,
      campus: program.campusName ?? "",
      overall: RISK_STATUS_LABELS[program.status],
      issues: program.openIssueCount,
      unresolved: program.unresolvedOutcomeCount,
    };
    for (const metric of CPL_METRICS) {
      const m = program.metrics[metric];
      row[`${metric}-rate`] = m && m.denominator > 0 ? m.percentage : "";
      row[`${metric}-benchmark`] = m?.benchmark ?? "";
      row[`${metric}-status`] = m ? RISK_STATUS_LABELS[m.status] : "";
      row[`${metric}-needed`] = m?.needed ?? "";
    }
    return row;
  });
  const sheet: XlsxSheet = { name: "Programs", columns, rows };

  const period = dashboard.period;
  const provenance = buildProvenanceSheet([
    ["Report"],
    ["Name", "Program dashboard"],
    ["Generated at", formatTimestamp(new Date())],
    ["Generated by", await describeGeneratedBy(req.user!.sub)],
    ["Rows", String(rows.length)],
    ["Reporting periods"],
    ...(await describePeriods([
      { id: period.id, label: period.label, startDate: period.startDate, endDate: period.endDate },
    ])),
    ["Method"],
    [
      "Status",
      "Meeting / At risk / Off track are worked out from the stored results above: At risk means the program is below its benchmark but could still reach it if the students who can still move the rate succeed; Off track means it cannot, even in the best case. Nothing was recomputed for this export.",
    ],
  ]);
  await sendXlsx(res, `program-dashboard-${period.label}.xlsx`, [sheet, provenance]);
}

// ------------------------------------------------------------ recompute

registerJob({
  type: "CPL_RECOMPUTE",
  maxAttempts: 1,
  backoffMs: DEFAULT_BACKOFF_MS,
  handler: async ({ params }) => {
    const reportingPeriodId = Number(params.reportingPeriodId);
    await computeReportingPeriod(reportingPeriodId);
    await runValidation(reportingPeriodId);
    return { reportingPeriodId };
  },
});

/**
 * Refreshes the stored results for the period (compute, then validation) so the
 * dashboard reflects recent data changes. The compute is institution-wide and
 * slow, so it runs as a tracked job and is refused if the period was computed
 * moments ago — a director can't hammer it.
 */
export async function recompute(req: Request, res: Response) {
  const { reportingPeriodId } = req.query as unknown as DashboardQuery;
  if (!reportingPeriodId) throw ApiError.badRequest("reportingPeriodId is required");
  const institutionId = req.user!.institutionId;

  const period = await prisma.reportingPeriod.findFirst({
    where: { id: reportingPeriodId, institutionId },
  });
  if (!period) throw ApiError.notFound("Reporting period not found");
  await assertPeriodIsEditable(reportingPeriodId);

  const last = await prisma.cplCalculationResult.aggregate({
    where: { reportingPeriodId },
    _max: { computedAt: true },
  });
  const lastComputed = last._max.computedAt;
  if (
    lastComputed &&
    Date.now() - lastComputed.getTime() < RECOMPUTE_MIN_INTERVAL_MINUTES * 60_000
  ) {
    throw new ApiError(
      429,
      "RECOMPUTE_TOO_SOON",
      `Results for this period were computed less than ${RECOMPUTE_MIN_INTERVAL_MINUTES} minutes ago. Try again shortly.`,
    );
  }

  await runJob("CPL_RECOMPUTE", {
    institutionId,
    params: { reportingPeriodId },
    trigger: "MANUAL",
    requestedBy: req.user!.sub,
    rethrow: true,
  });
  sendData(res, await loadDashboard(req), 201);
}
