-- AlterTable
ALTER TABLE `notifications`
    MODIFY `type` ENUM('FOLLOW_UP_DUE', 'FOLLOW_UP_OVERDUE', 'VERIFICATION_REQUIRED', 'LICENSURE_RESULT_REQUIRED', 'VALIDATION_ERROR', 'IMPROVEMENT_PLAN_TASK_DUE', 'PROGRAM_BELOW_THRESHOLD', 'MISSING_OUTCOMES_DIGEST') NOT NULL,
    ADD COLUMN `message` TEXT NOT NULL;
